version: '3.8'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=DentalApplicationReact
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: dentalappreactpostgresql

  backend:
    build:
      context: .
      dockerfile: docker/Python/Dockerfile
    volumes:
      - .:/dentalapp
    ports:
      - '8000:8000'
    depends_on:
      - db
    container_name: dentalappreactbackend
    links:
      - 'db:dentalappreactpostgresql'
